/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ExperienceBlock = {
  _type: "experienceBlock";
  companyName?: string;
  position?: string;
  companyLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  location?: string;
  startDate?: string;
  endDate?: string;
  isCurrent?: boolean;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  technologies?: Array<string>;
};

export type TestimonialBlock = {
  _type: "testimonialBlock";
  author?: string;
  role?: string;
  quote?: string;
  authorImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BioBlock = {
  _type: "bioBlock";
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  fullName?: string;
  jobTitle?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    color?: string;
    _key: string;
  }>;
};

export type SkillsBlock = {
  _type: "skillsBlock";
  name?: string;
  category?: "frontend" | "backend" | "devops" | "soft";
  level?: "expert" | "proficient" | "Entry-Level";
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  color?: string;
};

export type ProjectBlock = {
  _type: "projectBlock";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
  tech?: Array<string>;
};

export type EducationBlock = {
  _type: "educationBlock";
  university?: string;
  degree?: string;
  startDate?: string;
  endDate?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type TabsSection = {
  _type: "tabsSection";
  tabs?: Array<{
    tabLabel?: string;
    content?: Array<
      | ({
          _key: string;
        } & ProjectBlock)
      | ({
          _key: string;
        } & EducationBlock)
      | ({
          _key: string;
        } & SkillsBlock)
      | ({
          _key: string;
        } & BioBlock)
      | ({
          _key: string;
        } & TestimonialBlock)
      | ({
          _key: string;
        } & ExperienceBlock)
    >;
    _key: string;
  }>;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  pageBuilder?: Array<
    {
      _key: string;
    } & TabsSection
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    title?: string;
    actionType?: "link" | "external" | "download" | "contact";
    contactEmail?: string;
    socialLinks?: Array<{
      platform?: string;
      url?: string;
      _key: string;
    }>;
    url?: string;
    file?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    isDropdown?: boolean;
    dropdownItems?: Array<{
      label?: string;
      url?: string;
      _key: string;
    }>;
    _type: "navItem";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ExperienceBlock
  | TestimonialBlock
  | BioBlock
  | SkillsBlock
  | ProjectBlock
  | EducationBlock
  | TabsSection
  | Home
  | SanityImageCrop
  | SanityImageHotspot
  | SanityFileAssetReference
  | Navigation
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src\sanity\lib\queries.ts
// Variable: PORTFOLIO_QUERY
// Query: {  "nav": *[_type == "navigation"] | order(_updatedAt desc)[0]{    ...,    items[] {      ...,      "fileUrl": file.asset->url    }  },  "home": *[_type == "home"][0] {    ...,    pageBuilder[] {      ...,      tabs[] {        ...,        content[] {          ...,          _type == "projectBlock" => { ..., "imageUrl": image.asset->url },          _type == "skillsBlock" => { ..., "iconUrl": icon.asset->url },          _type == "bioBlock" => { ..., "profileImageUrl": profileImage.asset->url },          _type == "testimonialBlock" => { ..., "authorImageUrl": authorImage.asset->url },          _type == "experienceBlock" => { ..., "companyLogoUrl": companyLogo.asset->url },          _type == "educationBlock" => { ..., "imageUrl": image.asset->url },        }      }    }  }}
export type PORTFOLIO_QUERY_RESULT = {
  nav: {
    _id: string;
    _type: "navigation";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    items: Array<{
      title?: string;
      actionType?: "contact" | "download" | "external" | "link";
      contactEmail?: string;
      socialLinks?: Array<{
        platform?: string;
        url?: string;
        _key: string;
      }>;
      url?: string;
      file?: {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
      };
      isDropdown?: boolean;
      dropdownItems?: Array<{
        label?: string;
        url?: string;
        _key: string;
      }>;
      _type: "navItem";
      _key: string;
      fileUrl: string | null;
    }> | null;
  } | null;
  home: {
    _id: string;
    _type: "home";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    heroTitle?: string;
    pageBuilder: Array<{
      _key: string;
      _type: "tabsSection";
      tabs: Array<{
        tabLabel?: string;
        content: Array<
          | {
              _key: string;
              _type: "bioBlock";
              profileImage?: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              fullName?: string;
              jobTitle?: string;
              description?: Array<{
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }>;
              socialLinks?: Array<{
                platform?: string;
                url?: string;
                color?: string;
                _key: string;
              }>;
              profileImageUrl: string | null;
            }
          | {
              _key: string;
              _type: "educationBlock";
              university?: string;
              degree?: string;
              startDate?: string;
              endDate?: string;
              description?: Array<{
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }>;
              imageUrl: null;
            }
          | {
              _key: string;
              _type: "experienceBlock";
              companyName?: string;
              position?: string;
              companyLogo?: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              location?: string;
              startDate?: string;
              endDate?: string;
              isCurrent?: boolean;
              description?: Array<{
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?:
                  | "blockquote"
                  | "h1"
                  | "h2"
                  | "h3"
                  | "h4"
                  | "h5"
                  | "h6"
                  | "normal";
                listItem?: "bullet" | "number";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }>;
              technologies?: Array<string>;
              companyLogoUrl: string | null;
            }
          | {
              _key: string;
              _type: "projectBlock";
              title?: string;
              description?: string;
              image?: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              link?: string;
              tech?: Array<string>;
              imageUrl: string | null;
            }
          | {
              _key: string;
              _type: "skillsBlock";
              name?: string;
              category?: "backend" | "devops" | "frontend" | "soft";
              level?: "Entry-Level" | "expert" | "proficient";
              icon?: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              color?: string;
              iconUrl: string | null;
            }
          | {
              _key: string;
              _type: "testimonialBlock";
              author?: string;
              role?: string;
              quote?: string;
              authorImage?: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              authorImageUrl: string | null;
            }
        > | null;
        _key: string;
      }> | null;
    }> | null;
  } | null;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "nav": *[_type == "navigation"] | order(_updatedAt desc)[0]{\n    ...,\n    items[] {\n      ...,\n      "fileUrl": file.asset->url\n    }\n  },\n  "home": *[_type == "home"][0] {\n    ...,\n    pageBuilder[] {\n      ...,\n      tabs[] {\n        ...,\n        content[] {\n          ...,\n          _type == "projectBlock" => { ..., "imageUrl": image.asset->url },\n          _type == "skillsBlock" => { ..., "iconUrl": icon.asset->url },\n          _type == "bioBlock" => { ..., "profileImageUrl": profileImage.asset->url },\n          _type == "testimonialBlock" => { ..., "authorImageUrl": authorImage.asset->url },\n          _type == "experienceBlock" => { ..., "companyLogoUrl": companyLogo.asset->url },\n          _type == "educationBlock" => { ..., "imageUrl": image.asset->url },\n        }\n      }\n    }\n  }\n}': PORTFOLIO_QUERY_RESULT;
  }
}
